### ISSUE TITLE
callback arguments

### ISSUE THREAD

**Issue by cjessett** [jherediagu/CodeAcademy-TDD-Gather#1]
(Simplify) [Here](https://github.com/jherediagu/CodeAcademy-TDD-Gather/blob/a029d2f994d397c0950e7939d15cbac77521e4a2/routes/index.js#L5) you can omit the `next` callback argument since it isn't used in the function.

**Comment by jherediagu** [comment]
thank you so much for your comments, it's already resolved.

Thank you!
