### ISSUE TITLE
findById

### ISSUE THREAD

**Issue by cjessett** [jherediagu/CodeAcademy-TDD-Gather#3]
(Simplify) [Here](https://github.com/jherediagu/CodeAcademy-TDD-Gather/blob/a029d2f994d397c0950e7939d15cbac77521e4a2/routes/index.js#L28) instead of querying all the items use `.findById()` and pass in the id of the requested item.

**Comment by jherediagu** [comment]
Thanks for your comment, I think it's better with the `findyId()` it's clearer and I don't have to use the `filter` to get just one. 

thank you!
